// Constants matching the Prisma enum ProductEventType exactly
export enum ProductEventType {
  VIEW = "VIEW",
  CART_ADD = "CART_ADD",
  ORDER_COMPLETED = "ORDER_COMPLETED",
  PRODUCT_CLICK = "PRODUCT_CLICK",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  CHECKOUT_STARTED = "CHECKOUT_STARTED",
  PURCHASE = "PURCHASE",
  SEARCH = "SEARCH",
  SEARCH_RESULT_CLICK = "SEARCH_RESULT_CLICK",
  CATEGORY_VIEW = "CATEGORY_VIEW",
  SHARE = "SHARE",
  IMPRESSION = "IMPRESSION"
}
